#!/bin/bash
[[ -d raw ]] || mkdir raw

update_makemehanzi() {
  echo Updating makemeahanzi ...
  local dir=raw/makemeahanzi
  if [[ ! -d "${dir}" ]]; then
    cd raw && git clone --depth 1 https://github.com/skishore/makemeahanzi.git && cd ..
  fi
  cd "${dir}" && git pull && cd ../..
}

update_dongchineselexicon() {
  echo Updating Dong Chinese\'s chinese-lexicon ...
  local dir=raw/chinese-lexicon
  if [[ ! -d "${dir}" ]]; then
    cd raw && git clone https://github.com/peterolson/chinese-lexicon.git && cd ..
  fi
  cd "${dir}" && git pull && cd ../..
}

update_cc_cedict() {
  echo Updating CC-CEDICT ...
  local dir=raw/cc-cedict
  mkdir -p "${dir}"
  wget -O "${dir}/cc-cedict.zip" 'https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.zip'
  unzip -d "${dir}" "${dir}/cc-cedict.zip"
}

update_unihan() {
  echo Updating Unihan ...
  local dir=raw/unihan
  mkdir -p "${dir}"
  wget -O "${dir}/unihan.zip" 'https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip'
  unzip -d "${dir}" "${dir}/unihan.zip"
}

update_standard() {
  echo Updating the Table of General Standard Chinese Characters ...
  local dir=raw/standard
  mkdir -p "${dir}"
  wget -O "${dir}/standard.json" 'https://zh.wikisource.org/w/api.php?action=query&titles=通用规范汉字表&prop=revisions&rvslots=main&rvprop=content&format=json'
}

update_subtlexch() {
  echo Updating SUBTLEX-CH ...
  local dir=raw/subtlex-ch
  mkdir -p "${dir}"
  wget -O "${dir}/subtlexch.zip" 'http://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexch/subtlexchchr.zip'
  unzip -d "${dir}" "${dir}/subtlexch.zip"
  iconv -f GB18030 -t UTF-8 "${dir}/SUBTLEX-CH-CHR" > "${dir}/SUBTLEX-CH-CHR.utf8"
  wget -O "${dir}/subtlexch131210.zip" 'http://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexch/subtlexch131210.zip'
  unzip -d "${dir}" "${dir}/subtlexch131210.zip"
}

update_bcc() {
  echo "Updating BCLU Chinese Corpus (filtered) ..."
  local dir=raw/bcc
  mkdir -p "${dir}"
  wget -O "${dir}/bcc.zip" 'https://www.plecoforums.com/download/global_wordfreq-release-no-hiragana-katakana-zip.2616/'
  unzip -d "${dir}" "${dir}/bcc.zip"
  mv "${dir}"/*.txt "${dir}/bcc.txt"
}

update_junda() {
  echo "Updating Jun Da's character frequency list ..."
  local dir=raw/junda
  mkdir -p "${dir}"
  wget -O "${dir}/CharFreq.tsv" 'https://lingua.mtsu.edu/chinese-computing/statistics/char/download.php?Which=MO'
  iconv -f GB18030 -t UTF-8 "${dir}/CharFreq.tsv" | grep -v '^/' > "${dir}/CharFreq-utf8.tsv"
}

update_hsk30() {
  echo Updating hsk30 ...
  local dir=raw/hsk30
  if [[ ! -d "${dir}" ]]; then
    cd raw && git clone --depth 1 https://github.com/elkmovie/hsk30.git && cd ..
  fi
  cd "${dir}" && git pull && cd ../..
}

case "$1" in
  make)
    update_makemehanzi
    ;;
  dong)
    update_dongchineselexicon
    ;;
  cc)
    update_cc_cedict
    ;;
  unihan)
    update_unihan
    ;;
  standard)
    update_standard
    ;;
  sub)
    update_subtlexch
    ;;
  bcc)
    update_bcc
    ;;
  junda)
    update_junda
    ;;
  hsk30)
    update_hsk30
    ;;
  *)
    echo "Unknown resource '$1'"
    echo "Available resources: make, dong, cc, unihan, standard, sub, bcc, junda, hsk30"
    ;;
esac
