#!/bin/bash
[[ -d raw ]] || mkdir raw

update_makemehanzi() {
  echo Updating makemeahanzi ...
  local dir=raw/makemeahanzi
  if [[ ! -d "${dir}" ]]; then
    cd raw && git clone --depth 1 https://github.com/skishore/makemeahanzi.git && cd ..
  fi
  cd "${dir}" && git pull && cd ../..
}

update_dongchineselexicon() {
  echo Updating Dong Chinese\'s chinese-lexicon ...
  local dir=raw/chinese-lexicon
  if [[ ! -d "${dir}" ]]; then
    cd raw && git clone https://github.com/peterolson/chinese-lexicon.git && cd ..
  fi
  cd "${dir}" && git pull && cd ../..
  echo "Please manually copy the 'hsk' array from 'statistics/hsk.js' to 'statistics/hsk.json'"
}

update_hskhsk() {
  echo Updating hskhsk ...
  local dir=raw/hskhsk
  mkdir -p "${dir}"
  for i in {1..6}; do
    wget -O "${dir}/${i}.tsv" "https://raw.githubusercontent.com/glxxyz/hskhsk.com/main/data/lists/HSK%20Official%20With%20Definitions%202012%20L${i}.txt"
  done
}

update_cc_cedict() {
  echo Updating CC-CEDICT ...
  local dir=raw/cc-cedict
  mkdir -p "${dir}"
  wget -O "${dir}/cc-cedict.zip" 'https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.zip'
  unzip -d "${dir}" "${dir}/cc-cedict.zip"
}

update_unihan() {
  echo Updating Unihan ...
  local dir=raw/unihan
  mkdir -p "${dir}"
  wget -O "${dir}/unihan.zip" 'https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip'
  unzip -d "${dir}" "${dir}/unihan.zip"
}

update_subtlexch() {
  echo Updating SUBTLEX-CH ...
  local dir=raw/subtlex-ch
  mkdir -p "${dir}"
  wget -O "${dir}/subtlexch131210.zip" 'http://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexch/subtlexch131210.zip'
  unzip -d "${dir}" "${dir}/subtlexch131210.zip"
}

update_bcc() {
  echo "Updating BCLU Chinese Corpus (filtered) ..."
  local dir=raw/bcc
  mkdir -p "${dir}"
  wget -O "${dir}/bcc.zip" 'https://www.plecoforums.com/download/global_wordfreq-release-no-hiragana-katakana-zip.2616/'
  unzip -d "${dir}" "${dir}/bcc.zip"
  mv "${dir}"/*.txt "${dir}/bcc.txt"
}

update_junda() {
  echo "Updating Jun Da's character frequency list ..."
  local dir=raw/junda
  mkdir -p "${dir}"
  wget -O "${dir}/CharFreq.tsv" 'https://lingua.mtsu.edu/chinese-computing/statistics/char/download.php?Which=MO'
  iconv -f GB18030 -t UTF-8 "${dir}/CharFreq.tsv" | grep -v '^/' > "${dir}/CharFreq-utf8.tsv"
}

update_ic() {
  echo "Updating Integrated Chinese vocab list ..."
  local dir=raw/integrated-chinese
  mkdir -p "${dir}"
  wget -O "${dir}/l1p1.zip" 'http://www.denisowski.org/Chinese/ICL1P1/icl1p1_all.zip'
  wget -O "${dir}/l1p2.zip" 'http://www.denisowski.org/Chinese/ICL1P2/icl1p2_all.zip'
  wget -O "${dir}/l2p1.zip" 'http://www.denisowski.org/Chinese/ICL2P1/icl2p1_all.zip'
  wget -O "${dir}/l2p2.zip" 'http://www.denisowski.org/Chinese/ICL2P2/icl2p2_all.zip'
  for x in "${dir}/*.zip"; do unzip "${x}" -d "${dir}"; done
}

case "$1" in
  make)
    update_makemehanzi
    ;;
  dong)
    update_dongchineselexicon
    ;;
  hsk)
    update_hskhsk
    ;;
  cc)
    update_cc_cedict
    ;;
  unihan)
    update_unihan
    ;;
  sub)
    update_subtlexch
    ;;
  bcc)
    update_bcc
    ;;
  junda)
    update_junda
    ;;
  ic)
    update_ic
    ;;
  *)
    echo "Unknown resource '$1'"
    echo "Available resources: make, dong, hsk, cc, unihan, sub, bcc, junda, ic"
    ;;
esac
